### ISSUE TITLE
部分应用会在请求时发送 Options 预检导致无法成功代理

### ISSUE THREAD

**Issue by xyxc0673** [diemus/azure-openai-proxy#1]
非常感谢作者的这个 Repo，不过遇到了 Options 请求的问题，请问这个有办法绕过吗？

**Comment by diemus** [comment]
Options 请求的问题是什么问题？没太看明白

**Comment by xyxc0673** [comment]
我测试到 AMA（一个 iOS 应用）和 OpenAI Translator 在发送请求的时候，都会先发一个 Options 请求去检查对应的 URL 是否支持该请求，然后因为 Options 请求没有 Body，就被直接返回了

**Comment by diemus** [comment]
我修复了一版，你再试试，直接相应options请求就行

**Comment by xyxc0673** [comment]
可以了，感谢

**Comment by xyxc0673** [comment]
不过不知道你会不会感觉 Azure 的 API 和 OpenAI 的 API 的响应速度有一点不同，Azure 需要等一会儿然后响应一大段，不像 OpenAI 一下子就能响应，一字一字出来

**Comment by diemus** [comment]
是的，这个问题好像误无解，azure的就是这样的，我一开始也研究了半天，还是为是代码的问题

**Comment by xyxc0673** [comment]
我之前还以为是设置的问题，要是 Azure 能把这个问题解决了就能完美替换 OpenAI 的了
