### ISSUE TITLE
請問預設是有 https 的嗎？

### ISSUE THREAD

**Issue by sujunmin** [diemus/azure-openai-proxy#10]
<img width="916" alt="image" src="https://user-images.githubusercontent.com/6415168/232000880-cbf24bc1-e9cf-4f26-bdce-f8986faa62c1.png">
<img width="968" alt="image" src="https://user-images.githubusercontent.com/6415168/232001189-c5955f72-3837-4a72-abda-90a2d178a735.png">

**Comment by diemus** [comment]
没有内置的https，需要你在前面自己加一个https代理

**Comment by sujunmin** [comment]
好的 看文件都是 https 謝謝！
