### ISSUE TITLE
support gpt-4

### ISSUE THREAD

**Issue by zhangzhaorui** [diemus/azure-openai-proxy#12]
老师您好，请问一下咱们现在这套代码 能支持azure上的gpt4 的模型吗？

**Comment by zhangzhaorui** [comment]
我还是按照gpt3.5-turbo的方式部署的，但是貌似不太可以
![image](https://user-images.githubusercontent.com/18107299/232418317-30cf5b11-2a60-42e0-8368-65f2bcef7e56.png)

**Comment by zhangzhaorui** [comment]
2023/04/17 07:53:12 proxying request [gpt-3.5-turbo] /v1/chat/completions -> https://bpd.openai.azure.com/openai/deployments/gpt-35-turbo/chat/completions?api-version=2023-03-15-preview
[GIN] 2023/04/17 - 07:53:14 | 404 |  1.720606504s |      172.26.0.1 | POST     "/v1/chat/completions"

**Comment by zhangzhaorui** [comment]
部署完之后还是找3.5的这个模型，请教您一下怎么使用 azure的 gpt4 的

**Comment by zdaiot** [comment]
@zhangzhaorui 请问您是怎么解决这个的呢？
