### ISSUE TITLE
在vercel里部署有什么特别的设置吗？

### ISSUE THREAD

**Issue by goldenhawksu** [diemus/azure-openai-proxy#16]
在vercel部署了一个，用默认的build配置，环境变量除了KEY没设置，其它都按文档里的配置了  https://azure-api-proxy.vercel.app/

测试语句(Key作了mask)，
curl https://azure-api-proxy.vercel.app/v1/chat/completions -H "Content-Type: application/json" -H "Authorization: Bearer c4b7de425xxxxxxxxxxxxxxxxxxxxxxx" -d '{ "model": "gpt-35-turbo",  "messages": [{"role": "user", "content": "Hello!"}]}'

返回，

The page could not be found

NOT_FOUND

是哪里没有做对吗？

**Comment by diemus** [comment]
vercel不是部署前端项目用的吗？这个是个后端项目
