### ISSUE TITLE
/v1/models, unsupported request, body is empty, http: proxy error: unsupported protocol scheme ""

### ISSUE THREAD

**Issue by norrisp90** [diemus/azure-openai-proxy#3]
Hi,
I am trying use the proxy with chatBot-UI (https://github.com/mckaywrigley/chatbot-ui). The proxy is running and chatBot-UI appears to be sending it requests, but I am getting a proxy log error on opening chatBot-UI:
azure-openai-proxy error:
```
[GIN] 2023/04/04 - 07:30:12 | 502 |     123.423µs |      xxx.xxx.x.x | GET      "/v1/models"
2023/04/04 07:30:12 unsupported request, body is empty
2023/04/04 07:30:12 http: proxy error: unsupported protocol scheme ""
```

chatbot-UI error:
```
Error fetching models.
Make sure your OpenAI API key is set in the bottom left of the sidebar.
If you completed this step, OpenAI may be experiencing issues.
```

Any suggestions what I may be doing wrong?

**Comment by diemus** [comment]
currently the proxy can only handle post request,  "/v1/models" does not supported yet. I can make a mock response in the future

**Comment by diemus** [comment]
or you can change to other web ui that does not request /v1/models

**Comment by diemus** [comment]
@norrisp90 hi, problems fixed, you can try again
