### ISSUE TITLE
Embeddings数组超过1个元素时微软接口会报错Too many inputs. The max number of inputs is 1. 

### ISSUE THREAD

**Issue by summerbuild** [diemus/azure-openai-proxy#7]
用如下方式访问时
```
curl https://xxx.openai.azure.com/openai/deployments/yyy/embeddings?api-version=2023-03-15-preview  \
  -H "Content-Type: application/json" \
  -H "api-key: 1112222" \
  -d '{
      "input": ["1","2"]
    }'
```
openai的接口没这个问题，可以传递多个元素，但用一些库比如llama-index的时候会自动传递多个元素过来，当input的这个数组有超过2个元素时微软接口会报错，返回Too many inputs. The max number of inputs is 1错误
解决办法：
把数组的元素全部拼接起来成一个str，微软官方说法是input最大可以到8k
详细可以看微软的官方说明：
https://learn.microsoft.com/en-us/azure/cognitive-services/openai/reference

**Comment by diemus** [comment]
这个推荐的连接符是空格吗

**Comment by diemus** [comment]
微软已修复此问题
