### ISSUE TITLE
Stream 中文字符截斷亂碼問題。

### ISSUE THREAD

**Issue by Sen-CaPoo** [diemus/azure-openai-proxy#8]
問題重現與其他語言解決方案參考:
[發生與此專案相同問題 ChatGPT-Next-Web](https://github.com/Yidadaa/ChatGPT-Next-Web/issues/507#issuecomment-1500971442)

不知道 Golang 是否有辦法解決 Stream 中文字符截斷的問題。

**Comment by diemus** [comment]
应该可以解决的，golang可以按字符串切割
